# How to create a basic array
This section covers np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3, 4, 5, 6]

In [4]:
np.array(my_list)

array([1, 2, 3, 4, 5, 6])

In [5]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [6]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [7]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
np.ones(2)

array([1., 1.])

In [9]:
np.zeros(2)

array([0., 0.])

In [10]:
np.empty(3)

array([0., 0., 0.])

In [11]:
np.ones(2, dtype=np.int8)

array([1, 1], dtype=int8)

# Adding, removing, and sorting elements

This section covers np.sort(), np.concatenate()

In [12]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [13]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [15]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [17]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?
